analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.016746
name: Mark Shead
opengraph: {}
purpose: []
typography_spectrum: 0.5954636528622359
