name: Mark Shead
favicon: null
layout_spectrum: 0.24403
typography_spectrum: 0.5954636528622359
title: Mark Shead
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25
  lightness: 0.41212282446213067
  saturation: 0.4771966945845634
  rhythmicContrast: 0.5
purpose: []
