analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25
  lightness: 0.41212282446213067
  rhythmicContrast: 0.5
  saturation: 0.4771966945845634
cta: {}
layout_spectrum: 0.053453
name: Mark Shead
opengraph: {}
purpose: []
typography_spectrum: 0.5954636528622359
