name: Mark Shead
favicon: null
layout_spectrum: 0.49668
typography_spectrum: 0.5954636528622359
title: Mark Shead
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b060a'
    - '#aeb4b4'
    - '#61625c'
    - '#ffefdf'
    - '#8b3d27'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
